FROM ocaml/opam:debian-11-ocaml-4.14
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
  libc6-dev libev-dev capnproto m4 pkg-config libsqlite3-dev libgmp-dev libffi-dev graphviz \
  gnupg curl ca-certificates netcat lsb-release git runc inotify-tools procps

RUN mv /usr/bin/opam-2.1 /usr/bin/opam && opam remote add origin 'https://opam.ocaml.org' --all-switches && opam remote remove default
RUN opam update && opam install dune.3.5.0 ppx_expect>=v0.14.1 prometheus ppx_sexp_conv dune-build-info lwt>=5.4.1 capnp-rpc-lwt>=1.2 capnp-rpc-net capnp-rpc-unix>=1.2 extunix>=0.3.2 logs conf-libev digestif>=0.8 fpath lwt-dllist prometheus-app>=1.1 cohttp-lwt-unix sqlite3 psq mirage-crypto>=0.8.5 ppx_deriving ppx_deriving_yojson astring fmt>=0.8.9 cmdliner>=1.1.1 tar-unix>=2.0.0 yojson sexplib sha memtrace tyxml session-cohttp-lwt routes>=2.0.0 current_ansi irmin-watcher hex github-unix opam-state current_incr ocluster multipart_form-lwt ansi csv crunch prometheus.1.2 prometheus-app.1.2 current_git current

RUN ( curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc > /etc/apt/trusted.gpg.d/ngrok.asc ) \
    && ( echo "deb [trusted=yes] https://ngrok-agent.s3.amazonaws.com buster main" > /etc/apt/sources.list.d/ngrok.list ) \
    && apt-get update --allow-insecure-repositories \
    && apt-get install ngrok --assume-yes \
    && rm -r /var/lib/apt/lists /var/cache/apt

WORKDIR /app
RUN git config --global user.name "ocaml" && git config --global user.email "ci"
ENV OCAMLRUNPARAM=a=2
ENTRYPOINT ["opam", "exec", "--"]
