FROM ocaml/opam:debian-11-ocaml-4.13@sha256:41a176aa60a2573e6d99c41c9250f3aac726f97ee630a581d58cf31ce8cb9e58
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
  libc6-dev libev-dev capnproto m4 pkg-config libsqlite3-dev libgmp-dev libffi-dev graphviz \
  gnupg curl ca-certificates netcat lsb-release git runc inotify-tools procps

RUN opam remote add origin 'https://opam.ocaml.org' --all-switches && opam remote remove default && opam update
RUN opam install dune>=2.8 ppx_expect>=v0.14.1 prometheus ppx_sexp_conv dune-build-info lwt>=5.4.1 capnp-rpc-lwt>=1.2 capnp-rpc-net capnp-rpc-unix>=1.2 extunix>=0.3.2 logs conf-libev digestif>=0.8 fpath lwt-dllist prometheus-app>=1.1 cohttp-lwt-unix sqlite3 psq mirage-crypto>=0.8.5 ppx_deriving ppx_deriving_yojson astring fmt>=0.8.9 cmdliner>=1.1.1 tar-unix>=2.0.0 yojson sexplib sha memtrace tyxml session-cohttp-lwt routes current_ansi irmin-watcher hex ocluster github-unix opam-state current_incr

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install docker-ce-cli --assume-yes \
    && rm -r /var/lib/apt/lists /var/cache/apt

RUN mkdir /app
WORKDIR /app

COPY ocluster/ /app/ocluster
RUN cd /app/ocluster && opam pin -ny . && opam install -y .

RUN mkdir /app/store

ENV PROGRESS_NO_TRUNC=1
ENTRYPOINT ["opam", "exec", "--", "ocluster-worker", "--obuilder-store=rsync:/app/store", "--state-dir=/app/state"]
